[tool.briefcase]
project_name = "Countdown"
bundle = "com.communitycomputing"
version = "0.0.1"
url = "https://stupid.frickin.website/countdown"
license = "Apache Software License"
author = 'Hans Kelson'
author_email = "hans@communitycomputing.net"

[tool.briefcase.app.countdown]
formal_name = "Countdown"
description = "A Simple Countdown Timer"
icon = "src/countdown/resources/countdown"
sources = ['src/countdown','chime.wav']
requires = ['pyglet']


[tool.briefcase.app.countdown.macOS]
requires = []

[tool.briefcase.app.countdown.linux]
requires = []
system_requires = []

[tool.briefcase.app.countdown.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.countdown.iOS]
requires = []

[tool.briefcase.app.countdown.android]
requires = []
